# Generated by Django 3.2.8 on 2021-11-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('original_price', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=50, null=True)),
                ('polarity', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
                ('word_counter', models.JSONField()),
            ],
        ),
    ]
